### ISSUE TITLE
Info to build steps

### ISSUE THREAD

**Issue by tedstriker** [leso-kn/epaper-central#1]
Hi there,
thank you for providing an alternative to all the ESP32 based OEPL implementations.
Unfortunately `cmake .` in the repo directory doesn't do the trick. I get the error:

```
CMake Error at CMakeLists.txt:60 (install):
  install DIRECTORY given no DESTINATION!


-- Configuring incomplete, errors occurred!
```

Could you give me a hint, how to build it?

**Comment by leso-kn** [comment]
Thanks for pointing this out :) This was actually a bug in the CMake configuration.

There's a new docs page now with [build instructions](https://epaper-central.readthedocs.io/en/latest/building.html) and I've created a patch release with a fix for `cmake .` ([v0.1.1](https://github.com/leso-kn/epaper-central/releases/tag/v0.1.1))
